spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/covinfo?useTimezone=true&serverTimezone=UTC
    pool-size: 30
    username: root
    password: admin

  mail:
    host: localhost
    port: 25
    username: anything
    password: anything
