spring:
  profiles:
    active: test

  jpa:
    open-in-view: false

default:
  sender: noreply@covinfo.com
  confirmation-endpoint: http://localhost:8080/api/v1/users/confirmation

jwt:
  secret: this needs to be changed urgently
  expiration: 604800000

credentials:
  admin:
    email: admin@email.com
    password: super strong and secret password

  opendatasus:
    api-vacina:
      username: imunizacao_public
      password: qlto5t&7r_@+#Tlstigi