spring:
  profiles:
    active: test

  jpa:
    open-in-view: false

default:
  sender: noreply@covinfo.com
  confirmation-endpoint: http://localhost:8080/api/v1/users/confirmation

jwt:
  secret: this needs to be changed urgently
  expiration: 604800000

credentials:
  admin:
    email: admin@email.com
    password: super strong and secret password

  postmon-cep:
    url: https://api.postmon.com.br

  opendatasus:
    api-vacina:
      url: https://imunizacao-es.saude.gov.br
      username: imunizacao_public
      password: qlto5t&7r_@+#Tlstigi

    api-leitos:
      url: https://elastic-leitos.saude.gov.br/leito_ocupacao
      username: user-api-leitos
      password: aQbLL3ZStaTr38tj