spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DATABASE_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

default:
  sender: ${MAIL_USERNAME}
  confirmation-endpoint: ${CONFIRMATION_ENDPOINT}

jwt:
  secret: ${SECRET_KEY}
  expiration: ${EXPIRATION_TIME}

credentials:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
