spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/covinfo
    username: root
    password: admin
