spring:
  profiles:
    active: test

  jpa:
    open-in-view: false

default:
  sender: noreply@covinfo.com

jwt:
  secret: this needs to be changed urgently
  expiration: 604800000

credentials:
  admin:
    email: admin@email.com
    password: super strong and secret password
