spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/covinfo?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  mail:
    host: localhost
    port: 25
    username: anything
    password: anything
